# coding: utf-8

"""
    Ukraine Alert API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: support@stfalcon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import UkraineAlarm
from UkraineAlarm.models.v2_region_type import V2RegionType  # noqa: E501
from UkraineAlarm.rest import ApiException


class TestV2RegionType(unittest.TestCase):
    """V2RegionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2RegionType(self):
        """Test V2RegionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UkraineAlarm.models.v2_region_type.V2RegionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
