# coding: utf-8

"""
    Ukraine Alert API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: support@stfalcon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import UkraineAlarm
from UkraineAlarm.models.alert_region_model import AlertRegionModel  # noqa: E501
from UkraineAlarm.rest import ApiException


class TestAlertRegionModel(unittest.TestCase):
    """AlertRegionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertRegionModel(self):
        """Test AlertRegionModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UkraineAlarm.models.alert_region_model.AlertRegionModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
