# coding: utf-8

"""
    Ukraine Alert API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: support@stfalcon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RegionAlarmModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_id': 'str',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'duration': 'TimeSpan',
        'alert_type': 'AlertType',
        'region_name': 'str',
        'is_continue': 'bool'
    }

    attribute_map = {
        'region_id': 'regionId',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'duration': 'duration',
        'alert_type': 'alertType',
        'region_name': 'regionName',
        'is_continue': 'isContinue'
    }

    def __init__(self, region_id=None, start_date=None, end_date=None, duration=None, alert_type=None, region_name=None, is_continue=None):  # noqa: E501
        """RegionAlarmModel - a model defined in Swagger"""  # noqa: E501
        self._region_id = None
        self._start_date = None
        self._end_date = None
        self._duration = None
        self._alert_type = None
        self._region_name = None
        self._is_continue = None
        self.discriminator = None
        if region_id is not None:
            self.region_id = region_id
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if duration is not None:
            self.duration = duration
        if alert_type is not None:
            self.alert_type = alert_type
        if region_name is not None:
            self.region_name = region_name
        if is_continue is not None:
            self.is_continue = is_continue

    @property
    def region_id(self):
        """Gets the region_id of this RegionAlarmModel.  # noqa: E501


        :return: The region_id of this RegionAlarmModel.  # noqa: E501
        :rtype: str
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this RegionAlarmModel.


        :param region_id: The region_id of this RegionAlarmModel.  # noqa: E501
        :type: str
        """

        self._region_id = region_id

    @property
    def start_date(self):
        """Gets the start_date of this RegionAlarmModel.  # noqa: E501


        :return: The start_date of this RegionAlarmModel.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this RegionAlarmModel.


        :param start_date: The start_date of this RegionAlarmModel.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this RegionAlarmModel.  # noqa: E501


        :return: The end_date of this RegionAlarmModel.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this RegionAlarmModel.


        :param end_date: The end_date of this RegionAlarmModel.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def duration(self):
        """Gets the duration of this RegionAlarmModel.  # noqa: E501


        :return: The duration of this RegionAlarmModel.  # noqa: E501
        :rtype: TimeSpan
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this RegionAlarmModel.


        :param duration: The duration of this RegionAlarmModel.  # noqa: E501
        :type: TimeSpan
        """

        self._duration = duration

    @property
    def alert_type(self):
        """Gets the alert_type of this RegionAlarmModel.  # noqa: E501


        :return: The alert_type of this RegionAlarmModel.  # noqa: E501
        :rtype: AlertType
        """
        return self._alert_type

    @alert_type.setter
    def alert_type(self, alert_type):
        """Sets the alert_type of this RegionAlarmModel.


        :param alert_type: The alert_type of this RegionAlarmModel.  # noqa: E501
        :type: AlertType
        """

        self._alert_type = alert_type

    @property
    def region_name(self):
        """Gets the region_name of this RegionAlarmModel.  # noqa: E501


        :return: The region_name of this RegionAlarmModel.  # noqa: E501
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this RegionAlarmModel.


        :param region_name: The region_name of this RegionAlarmModel.  # noqa: E501
        :type: str
        """

        self._region_name = region_name

    @property
    def is_continue(self):
        """Gets the is_continue of this RegionAlarmModel.  # noqa: E501


        :return: The is_continue of this RegionAlarmModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_continue

    @is_continue.setter
    def is_continue(self, is_continue):
        """Sets the is_continue of this RegionAlarmModel.


        :param is_continue: The is_continue of this RegionAlarmModel.  # noqa: E501
        :type: bool
        """

        self._is_continue = is_continue

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegionAlarmModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegionAlarmModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
